/* Copyright (C) 2026 The Qt Company Ltd.
 *
 * SPDX-License-Identifier: LicenseRef-Qt-Commercial OR GPL-3.0-only
*/

#include "init.h"
#include "updateoperations.h"

#include <QDir>
#include <QObject>
#include <QTest>
#include <QFile>
#include <QTextStream>

using namespace KDUpdater;
using namespace QInstaller;

class tst_mkdiroperationtest : public QObject
{
    Q_OBJECT

private slots:
    void initTestCase()
    {
       QInstaller::init();
       QString path = QDir::current().path() + QDir::toNativeSeparators("/test");
       if (QDir(path).exists()) {
           QFAIL("Remove test folder first!");
       }
    }

    void testMissingArguments()
    {
        MkdirOperation op;

        QVERIFY(op.testOperation());
        QVERIFY(!op.performOperation());

        QCOMPARE(UpdateOperation::Error(op.error()), UpdateOperation::InvalidArguments);
        QCOMPARE(op.errorString(), QString("Invalid arguments in Mkdir: 0 arguments given, 1 to 3 "
            "arguments expected in the form: <file to remove> [UNDOOPERATION, \"\"]."));
    }

    void testCreateDirectory_data()
    {
        QTest::addColumn<QString>("directory");
        QTest::addColumn<bool>("overrideUndo");
        QTest::newRow("/test") << "/test" << false;
        QTest::newRow("/test/test") << "/test/test" << false;
        QTest::newRow("/test/test/test") << "/test/test/test" << false;
        QTest::newRow("no undo") << "/test" << true;
    }

    void testCreateDirectory()
    {
        QFETCH(QString, directory);
        QFETCH(bool, overrideUndo);

        QString path = QDir::current().path() + QDir::toNativeSeparators(directory);

        QVERIFY2(!QDir(path).exists(), path.toLatin1());
        MkdirOperation op;
        op.setArguments(QStringList() << path);
        if (overrideUndo)
            op.setArguments(op.arguments() << QLatin1String("UNDOOPERATION"));
        op.backup();
        QVERIFY2(op.performOperation(), op.errorString().toLatin1());
        QVERIFY2(QDir(path).exists(), path.toLatin1());
        QVERIFY2(op.undoOperation(), op.errorString().toLatin1());
        if (overrideUndo) {
            QVERIFY2(QDir(path).exists(), path.toLatin1());
            QVERIFY(QDir(path).removeRecursively());
        } else {
            QVERIFY2(!QDir(path).exists(), path.toLatin1());
        }
    }

    void testCreateDirectory_customFile_data()
    {
         QTest::addColumn<QString>("directory");
         QTest::addColumn<QString>("filename");
         QTest::newRow("/test") << "/test" << "/test/file.txt";
         QTest::newRow("/test/test") << "/test/test" << "/test/file.txt";
         QTest::newRow("/test/test/test") << "/test/test/test" << "/test/test/test/file.txt";
    }

    void testCreateDirectory_customFile()
    {
        QFETCH(QString, directory);
        QFETCH(QString, filename);
        QString path = QDir::current().path() + QDir::toNativeSeparators(directory);
        QString filepath = QDir::current().path() + QDir::toNativeSeparators(filename);

        QVERIFY2(!QDir(path).exists(), path.toLatin1());
        MkdirOperation op;
        op.setArguments(QStringList() << path);
        op.backup();
        QVERIFY2(op.performOperation(), op.errorString().toLatin1());
        QVERIFY2(QDir(path).exists(), path.toLatin1());
        QFile file(filepath);
        file.open(QIODevice::WriteOnly | QIODevice::Text);
        QTextStream out(&file);
        out << "This file is generated by QTest\n";
        file.close();
        QVERIFY2(!op.undoOperation(), op.errorString().toLatin1());
        QVERIFY2(file.exists(), filepath.toLatin1());
        QVERIFY2(QDir(filepath).remove(filepath), "Cannot remove file");
        QVERIFY2(!file.exists(), filepath.toLatin1());
        QVERIFY2(op.undoOperation(), op.errorString().toLatin1());
        QVERIFY2(!QDir(path).exists(), path.toLatin1());
    }

    void testCreateDirectory_customFile_force_data()
    {
        testCreateDirectory_customFile_data();
    }

    void testCreateDirectory_customFile_force()
    {
        QFETCH(QString, directory);
        QFETCH(QString, filename);
        QString path = QDir::current().path() + QDir::toNativeSeparators(directory);
        QString filepath = QDir::current().path() + QDir::toNativeSeparators(filename);

        QVERIFY2(!QDir(path).exists(), path.toLatin1());
        MkdirOperation op;
        op.setArguments(QStringList() << path);
        op.setValue("forceremoval",true);
        op.backup();
        QVERIFY2(op.performOperation(), op.errorString().toLatin1());
        QVERIFY2(QDir(path).exists(), path.toLatin1());
        QFile file(filepath);
        file.open(QIODevice::WriteOnly | QIODevice::Text);
        QTextStream out(&file);
        out << "This file is generated by QTest\n";
        file.close();
        QVERIFY2(op.undoOperation(), op.errorString().toLatin1());
        QVERIFY2(!file.exists(), path.toLatin1());
    }
};

QTEST_MAIN(tst_mkdiroperationtest)

#include "tst_mkdiroperationtest.moc"
